version: '3'

services:

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db
    ports:
      - 80:3000

  db:
    container_name: db
    image: postgres:alpine
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_DB = ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
