version: '3.9'

services:

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:3000

  db:
    container_name: db
    image: postgres:alpine
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_DB = ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
